/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCerebroRouteImport } from './routes/_authenticated/cerebro'
import { Route as AuthenticatedConcorrentesRouteImport } from './routes/_authenticated/concorrentes'
import { Route as AuthenticatedCriarRouteImport } from './routes/_authenticated/criar'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedMetricasRouteImport } from './routes/_authenticated/metricas'
import { Route as AuthenticatedPautasRouteImport } from './routes/_authenticated/pautas'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/_authenticated/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/_authenticated/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCerebroRoute = AuthenticatedCerebroRouteImport.update({
  id: '/_authenticated/cerebro',
  path: '/cerebro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConcorrentesRoute =
  AuthenticatedConcorrentesRouteImport.update({
    id: '/_authenticated/concorrentes',
    path: '/concorrentes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCriarRoute = AuthenticatedCriarRouteImport.update({
  id: '/_authenticated/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/_authenticated/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMetricasRoute = AuthenticatedMetricasRouteImport.update({
  id: '/_authenticated/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPautasRoute = AuthenticatedPautasRouteImport.update({
  id: '/_authenticated/pautas',
  path: '/pautas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/cerebro': typeof AuthenticatedCerebroRoute
  '/concorrentes': typeof AuthenticatedConcorrentesRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/metricas': typeof AuthenticatedMetricasRoute
  '/pautas': typeof AuthenticatedPautasRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/cerebro': typeof AuthenticatedCerebroRoute
  '/concorrentes': typeof AuthenticatedConcorrentesRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/metricas': typeof AuthenticatedMetricasRoute
  '/pautas': typeof AuthenticatedPautasRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/cerebro': typeof AuthenticatedCerebroRoute
  '/_authenticated/concorrentes': typeof AuthenticatedConcorrentesRoute
  '/_authenticated/criar': typeof AuthenticatedCriarRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/metricas': typeof AuthenticatedMetricasRoute
  '/_authenticated/pautas': typeof AuthenticatedPautasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ajustes'
    | '/calendario'
    | '/cerebro'
    | '/concorrentes'
    | '/criar'
    | '/kanban'
    | '/metricas'
    | '/pautas'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ajustes'
    | '/calendario'
    | '/cerebro'
    | '/concorrentes'
    | '/criar'
    | '/kanban'
    | '/metricas'
    | '/pautas'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/ajustes'
    | '/_authenticated/calendario'
    | '/_authenticated/cerebro'
    | '/_authenticated/concorrentes'
    | '/_authenticated/criar'
    | '/_authenticated/kanban'
    | '/_authenticated/metricas'
    | '/_authenticated/pautas'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCerebroRoute: typeof AuthenticatedCerebroRoute
  AuthenticatedConcorrentesRoute: typeof AuthenticatedConcorrentesRoute
  AuthenticatedCriarRoute: typeof AuthenticatedCriarRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedMetricasRoute: typeof AuthenticatedMetricasRoute
  AuthenticatedPautasRoute: typeof AuthenticatedPautasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cerebro': {
      id: '/_authenticated/cerebro'
      path: '/cerebro'
      fullPath: '/cerebro'
      preLoaderRoute: typeof AuthenticatedCerebroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/concorrentes': {
      id: '/_authenticated/concorrentes'
      path: '/concorrentes'
      fullPath: '/concorrentes'
      preLoaderRoute: typeof AuthenticatedConcorrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/criar': {
      id: '/_authenticated/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof AuthenticatedCriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/metricas': {
      id: '/_authenticated/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof AuthenticatedMetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pautas': {
      id: '/_authenticated/pautas'
      path: '/pautas'
      fullPath: '/pautas'
      preLoaderRoute: typeof AuthenticatedPautasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCerebroRoute: AuthenticatedCerebroRoute,
  AuthenticatedConcorrentesRoute: AuthenticatedConcorrentesRoute,
  AuthenticatedCriarRoute: AuthenticatedCriarRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedMetricasRoute: AuthenticatedMetricasRoute,
  AuthenticatedPautasRoute: AuthenticatedPautasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
