/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCerebroRouteImport } from './routes/_authenticated/cerebro'
import { Route as AuthenticatedConcorrentesRouteImport } from './routes/_authenticated/concorrentes'
import { Route as AuthenticatedCriarRouteImport } from './routes/_authenticated/criar'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedMetricasRouteImport } from './routes/_authenticated/metricas'
import { Route as AuthenticatedPautasRouteImport } from './routes/_authenticated/pautas'
import { Route as AuthenticatedPostIdRouteImport } from './routes/_authenticated/post.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCerebroRoute = AuthenticatedCerebroRouteImport.update({
  id: '/cerebro',
  path: '/cerebro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConcorrentesRoute =
  AuthenticatedConcorrentesRouteImport.update({
    id: '/concorrentes',
    path: '/concorrentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCriarRoute = AuthenticatedCriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetricasRoute = AuthenticatedMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPautasRoute = AuthenticatedPautasRouteImport.update({
  id: '/pautas',
  path: '/pautas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostIdRoute = AuthenticatedPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/cerebro': typeof AuthenticatedCerebroRoute
  '/concorrentes': typeof AuthenticatedConcorrentesRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/metricas': typeof AuthenticatedMetricasRoute
  '/pautas': typeof AuthenticatedPautasRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/cerebro': typeof AuthenticatedCerebroRoute
  '/concorrentes': typeof AuthenticatedConcorrentesRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/metricas': typeof AuthenticatedMetricasRoute
  '/pautas': typeof AuthenticatedPautasRoute
  '/': typeof AuthenticatedIndexRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/cerebro': typeof AuthenticatedCerebroRoute
  '/_authenticated/concorrentes': typeof AuthenticatedConcorrentesRoute
  '/_authenticated/criar': typeof AuthenticatedCriarRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/metricas': typeof AuthenticatedMetricasRoute
  '/_authenticated/pautas': typeof AuthenticatedPautasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/post/$id': typeof AuthenticatedPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ajustes'
    | '/calendario'
    | '/cerebro'
    | '/concorrentes'
    | '/criar'
    | '/kanban'
    | '/metricas'
    | '/pautas'
    | '/post/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ajustes'
    | '/calendario'
    | '/cerebro'
    | '/concorrentes'
    | '/criar'
    | '/kanban'
    | '/metricas'
    | '/pautas'
    | '/'
    | '/post/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ajustes'
    | '/_authenticated/calendario'
    | '/_authenticated/cerebro'
    | '/_authenticated/concorrentes'
    | '/_authenticated/criar'
    | '/_authenticated/kanban'
    | '/_authenticated/metricas'
    | '/_authenticated/pautas'
    | '/_authenticated/'
    | '/_authenticated/post/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cerebro': {
      id: '/_authenticated/cerebro'
      path: '/cerebro'
      fullPath: '/cerebro'
      preLoaderRoute: typeof AuthenticatedCerebroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concorrentes': {
      id: '/_authenticated/concorrentes'
      path: '/concorrentes'
      fullPath: '/concorrentes'
      preLoaderRoute: typeof AuthenticatedConcorrentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criar': {
      id: '/_authenticated/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof AuthenticatedCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metricas': {
      id: '/_authenticated/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof AuthenticatedMetricasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pautas': {
      id: '/_authenticated/pautas'
      path: '/pautas'
      fullPath: '/pautas'
      preLoaderRoute: typeof AuthenticatedPautasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post/$id': {
      id: '/_authenticated/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof AuthenticatedPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCerebroRoute: typeof AuthenticatedCerebroRoute
  AuthenticatedConcorrentesRoute: typeof AuthenticatedConcorrentesRoute
  AuthenticatedCriarRoute: typeof AuthenticatedCriarRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedMetricasRoute: typeof AuthenticatedMetricasRoute
  AuthenticatedPautasRoute: typeof AuthenticatedPautasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPostIdRoute: typeof AuthenticatedPostIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCerebroRoute: AuthenticatedCerebroRoute,
  AuthenticatedConcorrentesRoute: AuthenticatedConcorrentesRoute,
  AuthenticatedCriarRoute: AuthenticatedCriarRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedMetricasRoute: AuthenticatedMetricasRoute,
  AuthenticatedPautasRoute: AuthenticatedPautasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPostIdRoute: AuthenticatedPostIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
